### ISSUE TITLE
Add devcontainer definition

### ISSUE THREAD

**Issue by o-lukas** [homebridge/homebridge-plugin-template#48] opened 2023-02-22 20:20 UTC
**Is your feature request related to a problem? Please describe:**
The main benefit of the devcontainers for me is that I have everything set up and ready to go after a few minutes and do not have to struggle with setting up node, homebridge, etc. So I went with creating a devcontainer which contains a basic homebridge instance already set up and ready to use. 

**Describe the solution you'd like:**
Add a ready-to-use devcontainer definition.

**Describe alternatives you've considered:**
None

**Additional context:**
I prepared a branch which contains the definition files needed to get it working. I can not push it because of permissions but you can check this [repository](https://github.com/o-lukas/homebridge-smartthings-tv/tree/main/.devcontainer) for the definition I used for my first plugin. If you tell me how to publish the branch I prepared I can do this of course so you can see the definition without my plugin specific stuff.

**Comment by bwp91** [comment] 2023-07-22 00:28
Closing issue as PR is open here
https://github.com/homebridge/homebridge-plugin-template/pull/54

I have copied your original text here into the PR description.

I realise the issue isn't resolved until the PR gets merged in but I prefer just having the PR open on its own without an issue too!

See you on the PR!

**Closed by bwp91** 2023-07-22 00:28 UTC
Labels: enhancement
